pub const NUMBER_OF_VERBOSE_TRIES: u64 = 30;
pub const PREIMAGE_PREFIX_LEN: usize = 16;
pub const BIRTHDAYS_PREFIX_LEN: usize = 32;
pub const PREIMAGE_HASH_COUNT: u64 = 1 << PREIMAGE_PREFIX_LEN;
pub const BIRTHDAYS_HASH_COUNT: u64 = 1 << BIRTHDAYS_PREFIX_LEN;
pub const PROBABILITY: f32 = 0.95;
